### ISSUE TITLE
Divide folds

### ISSUE THREAD

**Issue by wjczf123** [mark-xhchen/IE-CNN#1]
I notice that you use a different division from Xia 19. Though you also use 9:1 division. Can you report a result which uses division from Xia19. Thank you!

**Comment by mark-xhchen** [comment]
The division scheme is the same as Xia 19, though still with different divisions. The reported results of Xia19's approach in our paper are tested on our divisions, so if you only need to know the exact difference between these two approaches, this should be enough. 

I am sorry that I don't have the results of our approach testing on Xia19's divisions since I directly randomly divide the whole dataset, but I think that the average results should be quite similar no matter what division you use to test the approaches since I have also tested our approach several times on different random divisions.

**Comment by wjczf123** [comment]
OK. Thank you a lot.
